models:
  - name: "Base BERT"
    model_path: "princeton-logion/logion-bert-base"
    type: "bert"
    tokenizer_path: "princeton-logion/logion-bert-base"

  - name: "Plato BERT"
    model_path: "princeton-logion/logion-bert-plato"
    type: "bert"
    tokenizer_path: "princeton-logion/logion-bert-base"

  - name: "ATE BERT"
    model_path: "princeton-logion/logion-bert-ate"
    type: "bert"
    tokenizer_path: "princeton-logion/logion-bert-base"

  - name: "Tiresias V1 (Char)"
    model_path: "princeton-logion/char-model-linear-40"
    type: "canine"

  - name: "Tiresias V2 (Char)"
    model_path: "princeton-logion/char-model-linear-30"
    type: "canine"

lev_filter:
   lev1: "https://huggingface.co/datasets/princeton-logion/lev-filters/resolve/main/1.npy"
   lev2: "https://huggingface.co/datasets/princeton-logion/lev-filters/resolve/main/2.npy"
   lev3: "https://huggingface.co/datasets/princeton-logion/lev-filters/resolve/main/3.npy"
